#Tool Paths Configuration
#Thu Mar 20 17:25:24 PKT 2025
samtools=/home/iffy/NetBeansProjects/NGSGradle/app/bin/samtools-1.20
bwa=/home/iffy/NetBeansProjects/NGSGradle/app/bin/bwa-0.7.18
snpeff=/home/iffy/NetBeansProjects/NGSGradle/app/bin/snpEff/snpEff.jar
GATK=/home/iffy/NetBeansProjects/NGSGradle/app/bin/gatk-4.6.0.0
STAR=/home/iffy/NetBeansProjects/NGSGradle/app/bin/STAR_2.7.11b/Linux_x86_64
fastqc=/home/iffy/NetBeansProjects/NGSGradle/app/bin/FastQC
bcftools=/home/iffy/NetBeansProjects/NGSGradle/app/bin/bcftools-1.20
ensembl-vep=/home/iffy/NetBeansProjects/NGSGradle/app/bin/ensembl-vep-release-113
Trimmomatic=/home/iffy/NetBeansProjects/NGSGradle/app/bin/Trimmomatic-0.39/trimmomatic-0.39.jar
IGV=/home/iffy/NetBeansProjects/NGSGradle/app/bin/IGV_Linux_2.18.4
subread=/home/iffy/NetBeansProjects/NGSGradle/app/bin/subread-2.0.7-Linux-x86_64/bin
picard=/home/iffy/NetBeansProjects/NGSGradle/app/bin/picard.jar
fastp=/home/iffy/NetBeansProjects/NGSGradle/app/bin/fastp-0.24.0
