#Tool Paths Configuration
#Sun Oct 26 18:48:46 PKT 2025
GATK=/home/iffy/NetBeansProjects/NGSGradle/app/bin/gatk-4.6.2.0
HTS=/home/iffy/NetBeansProjects/NGSGradle/app/bin/htslib-1.22
IGV=/home/iffy/NetBeansProjects/NGSGradle/app/bin/IGV_Linux_2.19.4
STAR=/home/iffy/NetBeansProjects/NGSGradle/app/bin/STAR_2.7.11b/Linux_x86_64
Trimmomatic=/home/iffy/NetBeansProjects/NGSGradle/app/bin/Trimmomatic-0.39/trimmomatic-0.39.jar
annovar=/home/iffy/NetBeansProjects/NGSGradle/app/bin/annovar
bcftools=/home/iffy/NetBeansProjects/NGSGradle/app/bin/bcftools-1.22
bwa=/home/iffy/NetBeansProjects/NGSGradle/app/bin/bwa-0.7.19
ensembl-vep=/home/iffy/NetBeansProjects/NGSGradle/app/bin/ensembl-vep-release-114
fastp=/home/iffy/NetBeansProjects/NGSGradle/app/bin/fastp-1.0.1
fastqc=/home/iffy/NetBeansProjects/NGSGradle/app/bin/FastQC
multiqc=/home/iffy/NetBeansProjects/NGSGradle/app/bin/MultiQC-1.30/multiqc
picard=/home/iffy/NetBeansProjects/NGSGradle/app/bin/picard.jar
samtools=/home/iffy/NetBeansProjects/NGSGradle/app/bin/samtools-1.22
snpeff=/home/iffy/NetBeansProjects/NGSGradle/app/bin/snpEff
subread=/home/iffy/NetBeansProjects/NGSGradle/app/bin/subread-2.1.1-Linux-x86_64/bin
