/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package NGSGradle;


import java.awt.Graphics;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.*;
import java.util.List;
import java.util.Map;
/**
 *
 * @author iffy
 */
public class InputPathDialog extends javax.swing.JDialog {

    private DefaultListModel listModelSingle,listModelPair1,listModelPair2;
    private Map<String, List<String>> singlePathMap;
    private Map<String, Map<String, List<String>>> pairPathMap;
    public String selectedKey;
    boolean isPaired;
    /**
     * Creates new form InputPathDialog
     */
    
    public InputPathDialog(java.awt.Frame parent, boolean modal, Map<String, List<String>> singlePathMap) {
        super(parent, modal);
         this.singlePathMap = singlePathMap;
         isPaired=false;
         listModelSingle = new DefaultListModel();
         listModelPair1 = new DefaultListModel();
         listModelPair2  = new DefaultListModel();
    
         initComponents();
        
        singlePanel.setVisible(true);
        pairPanel.setVisible(false);
        
         // Populate ComboBox with Map keys
        pathOptionCombo.removeAllItems();
        pathOptionCombo.addItem("Select");
        for (String key : singlePathMap.keySet()) {
            pathOptionCombo.addItem(key);
        }
        
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

this.addWindowListener(new WindowAdapter() {
    @Override
    public void windowClosing(WindowEvent e) {
        if (pathOptionCombo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(InputPathDialog.this,
                "Please select a valid input path option before closing.",
                "Selection Required", JOptionPane.WARNING_MESSAGE);
        } else {
            dispose(); // allow closing
        }
    }
});

        
    }//Single
    
    public InputPathDialog(java.awt.Frame parent, boolean modal, Map<String, Map<String, List<String>>> pairPathMap, boolean isPaired) {
        super(parent, modal);
         this.pairPathMap = pairPathMap;
         this.isPaired=isPaired;
         listModelSingle = new DefaultListModel();
         listModelPair1 = new DefaultListModel();
        listModelPair2 = new DefaultListModel();
        initComponents();
        
        singlePanel.setVisible(false);
        pairPanel.setVisible(true);
        
         // Populate ComboBox with Map keys
        pathOptionCombo.removeAllItems();
        pathOptionCombo.addItem("Select");
        for (String key : pairPathMap.keySet()) {
            pathOptionCombo.addItem(key);
        }
        
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

this.addWindowListener(new WindowAdapter() {
    @Override
    public void windowClosing(WindowEvent e) {
        if (pathOptionCombo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(InputPathDialog.this,
                "Please select a valid input path option before closing.",
                "Selection Required", JOptionPane.WARNING_MESSAGE);
        } else {
                 selectedKey = (String) pathOptionCombo.getSelectedItem(); // Store the selected key
              
           setVisible(false);  // allow closing
        }
    }
});

        
        
    }//Pair

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel()
        {

            public void paintComponent(Graphics g){
                super.paintComponent(g);
                g.drawImage(NGSGradle.App.bgInstall, 0, 0, null);
            }
        }

        ;
        jLabel1 = new javax.swing.JLabel();
        pathOptionCombo = new javax.swing.JComboBox<>();
        nextB = new javax.swing.JButton();
        singlePanel = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        readSingleList = new javax.swing.JList<>(listModelSingle);
        jLabel2 = new javax.swing.JLabel();
        pairPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        readPair1List = new javax.swing.JList<>(listModelPair1);
        jScrollPane9 = new javax.swing.JScrollPane();
        readPair2List = new javax.swing.JList<>(listModelPair2);
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("INPUT PATHS");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Input Paths to Proceed:");

        pathOptionCombo.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        pathOptionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pathOptionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathOptionComboActionPerformed(evt);
            }
        });

        nextB.setText("NEXT");
        nextB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBActionPerformed(evt);
            }
        });

        singlePanel.setOpaque(false);

        readSingleList.setBorder(javax.swing.BorderFactory.createTitledBorder("All sample(s) single end reads"));
        readSingleList.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        readSingleList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane8.setViewportView(readSingleList);

        jLabel2.setText("Single Read:");

        javax.swing.GroupLayout singlePanelLayout = new javax.swing.GroupLayout(singlePanel);
        singlePanel.setLayout(singlePanelLayout);
        singlePanelLayout.setHorizontalGroup(
            singlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(singlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                    .addGroup(singlePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        singlePanelLayout.setVerticalGroup(
            singlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singlePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );

        pairPanel.setOpaque(false);

        readPair1List.setBorder(javax.swing.BorderFactory.createTitledBorder("All sample(s) read 1 only"));
        readPair1List.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        readPair1List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(readPair1List);

        readPair2List.setBorder(javax.swing.BorderFactory.createTitledBorder("All sample(s) read 2 only"));
        readPair2List.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jScrollPane9.setViewportView(readPair2List);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Read 1:");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Read 2:");

        javax.swing.GroupLayout pairPanelLayout = new javax.swing.GroupLayout(pairPanel);
        pairPanel.setLayout(pairPanelLayout);
        pairPanelLayout.setHorizontalGroup(
            pairPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pairPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pairPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
                    .addGroup(pairPanelLayout.createSequentialGroup()
                        .addGroup(pairPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane9))
                .addContainerGap())
        );
        pairPanelLayout.setVerticalGroup(
            pairPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pairPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathOptionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(nextB, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(singlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pairPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pathOptionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(nextB)))
                .addContainerGap(488, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 107, Short.MAX_VALUE)
                    .addComponent(singlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 107, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(52, Short.MAX_VALUE)
                    .addComponent(pairPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pathOptionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathOptionComboActionPerformed

        if (pathOptionCombo.getSelectedIndex()== 0){
        nextB.setEnabled(false);
        
        } else{
            nextB.setEnabled(true);
         selectedKey = (String) pathOptionCombo.getSelectedItem();
        if(!isPaired){//Single
        listModelSingle.clear();
       
       
        List<String> paths = singlePathMap.getOrDefault(selectedKey, List.of());
            
        for(String path:paths)
            listModelSingle.addElement(path);
        
        
        }else if (isPaired){
        
        listModelPair1.clear();
        listModelPair2.clear();
        // Fetch the map containing R1 and R2 lists
        Map<String, List<String>> pairedFiles = pairPathMap.get(selectedKey);

        if (pairedFiles != null) {
            // Get R1 and R2 lists
            List<String> pair1Paths = pairedFiles.getOrDefault("R1", List.of());
            List<String> pair2Paths = pairedFiles.getOrDefault("R2", List.of());

            // Populate JList for R1
            for (String path : pair1Paths) {
                listModelPair1.addElement(path);
            }

            // Populate JList for R2
            for (String path : pair2Paths) {
                listModelPair2.addElement(path);
            }
        }
        
        
        }
        }//else
        
        
        
        
    
        
        
        
    }//GEN-LAST:event_pathOptionComboActionPerformed
public String getSelectedKey() {
    
    return selectedKey;
}

    private void nextBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBActionPerformed
if (pathOptionCombo.getSelectedIndex() > 0) { // Ensure a valid selection
         selectedKey = (String) pathOptionCombo.getSelectedItem(); // Store the selected key
                
       this.setVisible(false);  // Close the dialog
        
    } else {
    
        JOptionPane.showMessageDialog(this, "Please select any input list!", "Warning", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_nextBActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InputPathDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InputPathDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InputPathDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InputPathDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                InputPathDialog dialog = new InputPathDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton nextB;
    private javax.swing.JPanel pairPanel;
    private javax.swing.JComboBox<String> pathOptionCombo;
    private javax.swing.JList<String> readPair1List;
    private javax.swing.JList<String> readPair2List;
    private javax.swing.JList<String> readSingleList;
    private javax.swing.JPanel singlePanel;
    // End of variables declaration//GEN-END:variables
}
