/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package NGSGradle;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.io.PrintWriter;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author iffy
 */
public class STARInternalFrame extends javax.swing.JInternalFrame {
    
    private File[] allFiles;
    private int clickedFlag = 0;
    private DefaultListModel listModelfasta, listModelreadSingle, listModelreadPair1, listModelreadPair2;
    private String fileMode;
    public STARInternalFrame() {
        listModelfasta = new DefaultListModel();
         listModelreadSingle = new DefaultListModel();
        listModelreadPair1 = new DefaultListModel();
        listModelreadPair2 = new DefaultListModel();
        
        initComponents();
        //ICONS:
        jLabel14.setIcon(App.icons[0]);
        jLabel19.setIcon(App.icons[3]);
        
         buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        jRadioButton1.setSelected(true);
        
        starStep1Panel.setVisible(false);
        starStep2Panel.setVisible(false);
        additionalPanel.setVisible(false);
        
        //DEFAULT VARIABLES
        fileMode="exFAT";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        STARPanel = new javax.swing.JPanel()
        {

            public void paintComponent(Graphics g){
                super.paintComponent(g);
                g.drawImage(NGSGradle.App.bgLoginMain, 0, 0, null);
            }
        }
        ;
        starStep1Panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        threadsTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGenomeDir = new javax.swing.JTextField();
        browseGenomeDir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        runModeTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        browseGenomeFastaFiles = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtGtfFiles = new javax.swing.JTextField();
        browseGtfFile = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        overhangTxt = new javax.swing.JTextField();
        buttonSTARAnalysis = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        additionalPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        exonParentTranscript = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        featureExon = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtFileChrStartEnd = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        genomeSAindex = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        genomeChrBin = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        genomeFastaList = new javax.swing.JList<>(listModelfasta);
        starStep2Panel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtGenomeDir1 = new javax.swing.JTextField();
        browseGenomeDir1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        buttonSTARAnalysis1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        twopassMode2 = new javax.swing.JComboBox<>();
        jLabel48 = new javax.swing.JLabel();
        outSAMtype2 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtOutputDir = new javax.swing.JTextField();
        browseOutputDir = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        readFilesInSingle = new javax.swing.JList<>(listModelreadSingle);
        jScrollPane5 = new javax.swing.JScrollPane();
        readFilesInPair1 = new javax.swing.JList<>(listModelreadPair1);
        jScrollPane6 = new javax.swing.JScrollPane();
        readFilesInPair2 = new javax.swing.JList<>(listModelreadPair2);
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel89 = new javax.swing.JLabel();
        fileSystemCombo = new javax.swing.JComboBox<>();
        jLabel90 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        outBAMsortingBinsN = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        outSAMmapqUnique = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("STAR");

        STARPanel.setBackground(new java.awt.Color(0, 0, 0));
        STARPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        starStep1Panel.setBackground(new java.awt.Color(0, 0, 0));
        starStep1Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Generating Genome Indexes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        starStep1Panel.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BASIC OPTIONS");

        threadsTxt.setText("1");
        threadsTxt.setToolTipText("number of threads to run STAR default: 1");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Genome Directory:");

        txtGenomeDir.setToolTipText("path to the directory where genome files are stored (for –runMode alignReads) or will be generated (for –runMode generateGenome)");

        browseGenomeDir.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        browseGenomeDir.setText("Browse");
        browseGenomeDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseGenomeDirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Run Mode:");

        runModeTxt.setText("genomeGenerate");
        runModeTxt.setToolTipText("type of the run default: alignReads");

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Genome Fasta Files:");

        browseGenomeFastaFiles.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        browseGenomeFastaFiles.setText("Browse");
        browseGenomeFastaFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseGenomeFastaFilesActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("GTF Files:");

        txtGtfFiles.setToolTipText("path to the GTF file with annotations");

        browseGtfFile.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        browseGtfFile.setText("Browse");
        browseGtfFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseGtfFileActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Over Hang:");

        overhangTxt.setText("100");
        overhangTxt.setToolTipText("int>0: length of the donor/acceptor sequence on each side of the junctions, ideally = (mate length - 1)");

        buttonSTARAnalysis.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        buttonSTARAnalysis.setText("Perform Analysis");
        buttonSTARAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSTARAnalysisActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("No. of Threads:");

        jLabel19.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ADVANCED OPTIONS:");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        additionalPanel.setBackground(new java.awt.Color(0, 0, 0));
        additionalPanel.setOpaque(false);

        jLabel22.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Annotations in GFF format:");

        jLabel24.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("--sjdbGTFtagExonParentTranscript");

        exonParentTranscript.setText("transcript_id");
        exonParentTranscript.setToolTipText("tag name to be used as exons’ transcript-parents  default: transcript_id");

        jLabel25.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("--sjdbGTFfeatureExon");

        featureExon.setText("exon");
        featureExon.setToolTipText("feature type in GTF file to be used as exons for building transcripts");

        jLabel27.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("--sjdbFileChrStartEnd ");

        jLabel28.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Using a list of annotated junctions:");

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtFileChrStartEnd.setText("-");
        txtFileChrStartEnd.setToolTipText("path to the files with genomic coordinates (chr <tab> start <tab> end <tab> strand) for the splice junction introns. Multiple files can be supplied wand will be concatenated.");

        jLabel29.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Very small Genome:");

        jLabel30.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText(" --genomeSAindexNbases ");

        genomeSAindex.setText("14");
        genomeSAindex.setToolTipText("length (bases) of the SA pre-indexing string. Typically between 10 and 15.");

        jLabel31.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Genome with a large number of reference:");

        genomeChrBin.setText("18");
        genomeChrBin.setToolTipText("=log2(chrBin), where chrBin is the size of the bins for genome storage: each chromosome will occupy an integer number of bins. ");

        jLabel32.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("--genomeChrBinNbits");

        javax.swing.GroupLayout additionalPanelLayout = new javax.swing.GroupLayout(additionalPanel);
        additionalPanel.setLayout(additionalPanelLayout);
        additionalPanelLayout.setHorizontalGroup(
            additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(additionalPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel22)
                    .addGroup(additionalPanelLayout.createSequentialGroup()
                        .addGroup(additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addGroup(additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel27)
                                .addComponent(jLabel28)
                                .addComponent(jLabel30))
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(additionalPanelLayout.createSequentialGroup()
                                .addComponent(exonParentTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(featureExon, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(additionalPanelLayout.createSequentialGroup()
                                .addComponent(txtFileChrStartEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(genomeSAindex, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(additionalPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel32)
                        .addGap(18, 18, 18)
                        .addComponent(genomeChrBin, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(480, Short.MAX_VALUE))
        );
        additionalPanelLayout.setVerticalGroup(
            additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(additionalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exonParentTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(featureExon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFileChrStartEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genomeSAindex, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genomeChrBin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(177, 177, 177))
        );

        genomeFastaList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        genomeFastaList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                genomeFastaListKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(genomeFastaList);

        javax.swing.GroupLayout starStep1PanelLayout = new javax.swing.GroupLayout(starStep1Panel);
        starStep1Panel.setLayout(starStep1PanelLayout);
        starStep1PanelLayout.setHorizontalGroup(
            starStep1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(starStep1PanelLayout.createSequentialGroup()
                .addGroup(starStep1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(starStep1PanelLayout.createSequentialGroup()
                        .addGap(595, 595, 595)
                        .addComponent(buttonSTARAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(starStep1PanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(starStep1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(additionalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(starStep1PanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(starStep1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(threadsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(runModeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(starStep1PanelLayout.createSequentialGroup()
                                .addGroup(starStep1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11))
                                .addGap(38, 38, 38)
                                .addComponent(overhangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(204, 204, 204)
                        .addGroup(starStep1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, starStep1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(starStep1PanelLayout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel6))
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, starStep1PanelLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(starStep1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(txtGtfFiles)
                            .addComponent(txtGenomeDir, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(starStep1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(browseGenomeDir)
                            .addComponent(browseGtfFile)
                            .addComponent(browseGenomeFastaFiles))))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        starStep1PanelLayout.setVerticalGroup(
            starStep1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(starStep1PanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addComponent(threadsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(runModeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(starStep1PanelLayout.createSequentialGroup()
                .addGroup(starStep1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(starStep1PanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(31, 31, 31)
                        .addGroup(starStep1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(overhangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(starStep1PanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(starStep1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtGenomeDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseGenomeDir))
                        .addGap(25, 25, 25)
                        .addGroup(starStep1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtGtfFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseGtfFile))
                        .addGap(23, 23, 23)
                        .addGroup(starStep1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(browseGenomeFastaFiles)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(34, 34, 34)
                .addComponent(additionalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(buttonSTARAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        starStep2Panel.setBackground(new java.awt.Color(0, 0, 0));
        starStep2Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Run Mapping Jobs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        starStep2Panel.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("No. of Threads:");

        jTextField2.setText("1");
        jTextField2.setToolTipText("number of threads to run STAR default: 1");

        jLabel16.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Genome Directory:");

        txtGenomeDir1.setEditable(false);
        txtGenomeDir1.setToolTipText("Path to the directory where genome files are stored (for –runMode alignReads) or will be generated (for –runMode generateGenome)");

        browseGenomeDir1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        browseGenomeDir1.setText("Browse");
        browseGenomeDir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseGenomeDir1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("BASIC OPTIONS:");

        buttonSTARAnalysis1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        buttonSTARAnalysis1.setText("Perform Analysis");
        buttonSTARAnalysis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSTARAnalysis1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Run Mode:");

        jTextField3.setEditable(false);
        jTextField3.setText("alignReads");
        jTextField3.setToolTipText("number of threads to run STAR default: 1");

        jLabel21.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Read Files Command:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gunzip -c", "zcat", "bzcat", "-" }));

        jLabel23.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("outSAMunmapped:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Within", "KeepPairs" }));

        jLabel26.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("outFileNamePrefix:");

        jTextField1.setText("SampleRead1");

        jLabel49.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("twopassMode:");

        twopassMode2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basic", "None" }));

        jLabel48.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("outSAMtype:");

        outSAMtype2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BAM SortedByCoordinate", "BAM Unsorted", "BAM Unsorted SortedByCoordinate", "SAM SortedByCoordinate", "SAM Unsorted", "SAM Unsorted SortedByCoordinate", "None" }));

        jLabel33.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("limitBAMsortRAM:");

        jTextField4.setText("0");
        jTextField4.setToolTipText("number of threads to run STAR default: 1");

        jLabel34.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("limitOutSJcollapsed:");

        jTextField5.setText("1000000");
        jTextField5.setToolTipText("number of threads to run STAR default: 1");

        jLabel35.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Output Directory:");

        txtOutputDir.setEditable(false);
        txtOutputDir.setToolTipText("Path to the directory where genome files are stored (for –runMode alignReads) or will be generated (for –runMode generateGenome)");

        browseOutputDir.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        browseOutputDir.setText("Browse");
        browseOutputDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseOutputDirActionPerformed(evt);
            }
        });

        jRadioButton1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("readFilesIn (Single end reads)");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("readFilesIn (Paired end reads)");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        readFilesInSingle.setBorder(javax.swing.BorderFactory.createTitledBorder("All sample(s) single end reads"));
        readFilesInSingle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        readFilesInSingle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                readFilesInSingleKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(readFilesInSingle);

        readFilesInPair1.setBorder(javax.swing.BorderFactory.createTitledBorder("All sample(s) read 1 only"));
        readFilesInPair1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        readFilesInPair1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                readFilesInPair1KeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(readFilesInPair1);

        readFilesInPair2.setBorder(javax.swing.BorderFactory.createTitledBorder("All sample(s) read 2 only"));
        readFilesInPair2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                readFilesInPair2KeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(readFilesInPair2);

        jButton8.setText("...");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton7.setText("...");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setText("...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel89.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(255, 255, 255));
        jLabel89.setText("File System:");

        fileSystemCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "exFAT", "NTFS" }));
        fileSystemCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSystemComboActionPerformed(evt);
            }
        });

        jLabel90.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(255, 255, 255));
        jLabel90.setText("NOTE: User can upload input files in *.fq , *.fa ,or *.gz zipped format");

        jLabel36.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("outBAMsortingBinsN:");

        outBAMsortingBinsN.setText("50");
        outBAMsortingBinsN.setToolTipText("number of threads to run STAR default: 1");

        jLabel37.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("outSAMmapqUnique:");

        outSAMmapqUnique.setText("255");
        outSAMmapqUnique.setToolTipText("number of threads to run STAR default: 1");

        javax.swing.GroupLayout starStep2PanelLayout = new javax.swing.GroupLayout(starStep2Panel);
        starStep2Panel.setLayout(starStep2PanelLayout);
        starStep2PanelLayout.setHorizontalGroup(
            starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(starStep2PanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, starStep2PanelLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(30, 30, 30)
                        .addComponent(outBAMsortingBinsN, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(891, 891, 891))
                    .addGroup(starStep2PanelLayout.createSequentialGroup()
                        .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(starStep2PanelLayout.createSequentialGroup()
                                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel49)
                                    .addComponent(jLabel33))
                                .addGap(30, 30, 30)
                                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(starStep2PanelLayout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(starStep2PanelLayout.createSequentialGroup()
                                            .addComponent(txtOutputDir, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)
                                            .addComponent(browseOutputDir))
                                        .addGroup(starStep2PanelLayout.createSequentialGroup()
                                            .addComponent(txtGenomeDir1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)
                                            .addComponent(browseGenomeDir1)))
                                    .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(starStep2PanelLayout.createSequentialGroup()
                                            .addComponent(jLabel37)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(outSAMmapqUnique, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(starStep2PanelLayout.createSequentialGroup()
                                            .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(starStep2PanelLayout.createSequentialGroup()
                                                    .addComponent(twopassMode2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel48))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, starStep2PanelLayout.createSequentialGroup()
                                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(47, 47, 47)
                                                    .addComponent(jLabel23)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel26))
                                                .addComponent(jLabel34))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField5)
                                                .addComponent(outSAMtype2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(149, 149, 149))
                    .addGroup(starStep2PanelLayout.createSequentialGroup()
                        .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(starStep2PanelLayout.createSequentialGroup()
                                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2))
                                .addGap(18, 18, 18)
                                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(starStep2PanelLayout.createSequentialGroup()
                                        .addComponent(jButton7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton8))
                                    .addGroup(starStep2PanelLayout.createSequentialGroup()
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 512, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(starStep2PanelLayout.createSequentialGroup()
                                .addComponent(jLabel89)
                                .addGap(30, 30, 30)
                                .addComponent(fileSystemCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, starStep2PanelLayout.createSequentialGroup()
                                .addComponent(buttonSTARAnalysis1)
                                .addGap(503, 503, 503)))
                        .addGap(36, 36, 36))))
        );
        starStep2PanelLayout.setVerticalGroup(
            starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, starStep2PanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtGenomeDir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseGenomeDir1))
                .addGap(18, 18, 18)
                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtOutputDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseOutputDir))
                .addGap(18, 18, 18)
                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(twopassMode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48)
                    .addComponent(outSAMtype2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(outSAMmapqUnique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37))
                    .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(outBAMsortingBinsN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel36)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileSystemCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel89))
                .addGap(18, 18, 18)
                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(starStep2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addComponent(buttonSTARAnalysis1)
                .addGap(28, 28, 28))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Step 1: Generate Genome Indexes (Recommended)","Step 2: Run Mapping Job(s)"}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Select appropriate option:");

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("HELP?");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        javax.swing.GroupLayout STARPanelLayout = new javax.swing.GroupLayout(STARPanel);
        STARPanel.setLayout(STARPanelLayout);
        STARPanelLayout.setHorizontalGroup(
            STARPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STARPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292))
            .addGroup(STARPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(starStep1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41))
            .addGroup(STARPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(STARPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(starStep2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(398, Short.MAX_VALUE)))
        );
        STARPanelLayout.setVerticalGroup(
            STARPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STARPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(STARPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(starStep1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(STARPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, STARPanelLayout.createSequentialGroup()
                    .addContainerGap(107, Short.MAX_VALUE)
                    .addComponent(starStep2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(231, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(STARPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1294, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseGenomeDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseGenomeDirActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setCurrentDirectory(new java.io.File("."));
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            
            String path = fileChooser.getSelectedFile().toString();
            
            txtGenomeDir.setText(path);
            
        }
        

    }//GEN-LAST:event_browseGenomeDirActionPerformed

    private void browseGenomeFastaFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseGenomeFastaFilesActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fasta Files (*.fa)", "fa"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Text Files (*.txt)", "txt"));
        
        fileChooser.setMultiSelectionEnabled(true);
        
        fileChooser.setAcceptAllFileFilterUsed(true);
        
        int option = fileChooser.showOpenDialog(this);
        
        if (option == JFileChooser.APPROVE_OPTION) {
            
            if (fileChooser.getSelectedFiles() != null) {
                allFiles = fileChooser.getSelectedFiles();
                
                for (int i = 0; i < allFiles.length; i++) {
                    listModelfasta.addElement(" \"" + allFiles[i].getAbsolutePath() + "\"");
                    // path += " \"" + allFiles[i].getAbsolutePath() + "\"";
                    //fileNameWithExtension.add(i, allFiles[i].getName());

                }

                //txtGenomeFastaFiles.setText(path);
            }
        }
    }//GEN-LAST:event_browseGenomeFastaFilesActionPerformed

    private void browseGtfFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseGtfFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("GTF Files (*.gtf)", "gtf"));
        /*  javax.swing.filechooser.FileFilter filter = new javax.swing.filechooser.FileFilter() {
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().toLowerCase().endsWith(".gtf");
            }

            public String getDescription() {
                return "GTF Files(*.gtf)";
            }
        };*/
        
        fileChooser.setAcceptAllFileFilterUsed(false);
        //  fileChooser.addChoosableFileFilter(filter);

        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            if (fileChooser.getSelectedFile() != null) {
                
                txtGtfFiles.setText(fileChooser.getSelectedFile().toString());
                
            }
        }
    }//GEN-LAST:event_browseGtfFileActionPerformed

    private void buttonSTARAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSTARAnalysisActionPerformed
        
        App.bar.setIndeterminate(true);
        App.sP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "In Progress....", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 15), new java.awt.Color(255, 255, 255)));
        
        SwingWorker<?, ?> worker = new SwingWorker<Integer, String>() {
            
            private int status;
            
            @Override
            protected Integer doInBackground() {
                try {
                    ProcessBuilder builder = new ProcessBuilder();
                    
                    List<String> cmdList = new ArrayList<String>();
                    // adding command and args to the list
                    cmdList.add("sh");
                    cmdList.add(System.getProperty("user.dir").concat("/bin/STAR.sh"));
                    cmdList.add(App.STAR_PATH); //$1
                    cmdList.add("Step1");
                    cmdList.add(threadsTxt.getText());
                    cmdList.add(runModeTxt.getText());
                    cmdList.add(txtGenomeDir.getText());
                    
                    String myArray = "";
                    for (int i = 0; i < genomeFastaList.getModel().getSize(); i++) {
                        myArray += genomeFastaList.getModel().getElementAt(i) + " ";
                    }
                    myArray = myArray.trim().replaceAll("\"", "");
                    cmdList.add(myArray);
                    cmdList.add(txtGtfFiles.getText());
                    cmdList.add(overhangTxt.getText());

                    //Optional for additional commands:
                    if (additionalPanel.isVisible()) {
                        cmdList.add(exonParentTranscript.getText());
                        cmdList.add(featureExon.getText());
                        cmdList.add(txtFileChrStartEnd.getText());
                        cmdList.add(genomeSAindex.getText());
                        cmdList.add(genomeChrBin.getText());
                        
                    } else {
                        //Default setting
                        cmdList.add("transcript id");
                        cmdList.add("exon");
                        cmdList.add("-");
                        cmdList.add("14");
                        cmdList.add("18");
                        
                    }

                    //publish("\r\nCommandExecuted: " + cmdList);
                    if (System.getProperty("os.name").startsWith("Windows")) {

                        //     builder.command("cmd.exe", "/c", "java -Xmx250m -classpath .;./sam-1.103.jar;./jbzip2-0.9.jar uk.ac.babraham.FastQC.FastQCApplication"+fastqPath.getText())
                        //     .directory(new File(STARpath));
                    } else {

                        //
                        //builder.command("sh", "-c", "cd", STARpath);
                        builder.command(cmdList);
                        // SshremoteConnection.executeShell(cmdList);

                        //https://hbctraining.github.io/Intro-to-rnaseq-hpc-O2/lessons/03_alignment.html
                    }
                    builder.redirectErrorStream(true);
                    
                    Process process = builder.start();
                    
                    InputStream is = process.getInputStream();
                    BufferedReader br = new BufferedReader(new InputStreamReader(is));
                    String line = null;
                    while ((line = br.readLine()) != null) {
                        App.LOGGER.info(line + "\r\n");
                        publish(line);
                        
                        if (line.endsWith("finished successfully")) {
                            
                            int x = JOptionPane.showConfirmDialog(null, "Do you also want to perform mapping?", "Confirmation Dialog", JOptionPane.YES_NO_OPTION);
                            if (x == JOptionPane.YES_OPTION) {
                                
                                jComboBox1.setSelectedIndex(2);
                                starStep1Panel.setVisible(false);
                                starStep2Panel.setVisible(true);
                                txtGenomeDir1.setText(txtGenomeDir.getText());
                                
                            }
                            
                        }
                        
                    }
                    if (!isCancelled()) {
                        status = process.waitFor();
                    }
                    
                    process.destroy();
                    //For 2 pass mapping
                    // List<Path> paths = App.findByFileExtension(Paths.get(txtGenomeDir.getText()), ".txt");
                    //paths.forEach(x -> App.textArea.append(x.toString()));

                    //RESULTS
                } catch (IOException | InterruptedException ex) {
                    ex.printStackTrace(new PrintWriter(App.stack));
                    App.LOGGER.error("\r\n ERROR in STAR analysis: " + App.stack);
                    App.textArea.append("\r\n ERROR in STAR analysis: " + App.stack);
                    
                }
                //catch

                return status;
            }
            
            @Override
            protected void process(java.util.List<String> messages) {
                
                for (String message : messages) {
                    App.textArea.append(message + "\n");
                }
            }
            
            @Override
            protected void done() {
                App.sP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 15), new java.awt.Color(255, 255, 255)));
                
                App.bar.setIndeterminate(false);
            }
            
        };
        
        worker.execute();
        

    }//GEN-LAST:event_buttonSTARAnalysisActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedIndex() == 1) {
            starStep1Panel.setVisible(true);
            starStep2Panel.setVisible(false);
        } else if (jComboBox1.getSelectedIndex() == 2) {
            starStep1Panel.setVisible(false);
            starStep2Panel.setVisible(true);
        } else {
            starStep1Panel.setVisible(false);
            starStep2Panel.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        
        try {
            Desktop.getDesktop().open(new File(System.getProperty("user.dir").concat("/bin/STAR-2.7.10a_alpha_220517/STARmanual.pdf")));
        } catch (IOException ex) {
            Logger.getLogger(STARInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void browseGenomeDir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseGenomeDir1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setCurrentDirectory(new java.io.File("."));
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            
            String path = fileChooser.getSelectedFile().toString();
            
            txtGenomeDir1.setText(path + "/");
            
        }
    }//GEN-LAST:event_browseGenomeDir1ActionPerformed

    private void buttonSTARAnalysis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSTARAnalysis1ActionPerformed
        App.bar.setIndeterminate(true);
        App.sP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "In Progress....", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 15), new java.awt.Color(255, 255, 255)));
        
        SwingWorker<?, ?> worker = new SwingWorker<Integer, String>() {
            
            private int status;
            
            @Override
            protected Integer doInBackground() {
                
                try {
                    ProcessBuilder builder = new ProcessBuilder();
                    
                    List<String> cmdList = new ArrayList<String>();
                    // adding command and args to the list
                    cmdList.add("sh");
                    cmdList.add(System.getProperty("user.dir").concat("/bin/STAR.sh"));
                    cmdList.add(App.STAR_PATH); //$1
                    cmdList.add("Step2"); //$2
                    cmdList.add(jTextField2.getText()); //--runThreadN
                    cmdList.add(jTextField3.getText()); //--runMode
                    cmdList.add(txtGenomeDir1.getText());//--genomeDir
                    if (jRadioButton1.isSelected()) {
                        
                        String myArray = "";
                        for (int i = 0; i < readFilesInSingle.getModel().getSize(); i++) {
                            
                            myArray += (readFilesInSingle.getModel().getElementAt(i) + ",").trim();
                        }
                        myArray = StringUtils.chop(myArray).replaceAll("\"", "");
                        myArray = "\"" + myArray + "\"";
                        
                        cmdList.add(myArray); //--readFilesIn 6

                    } else if (jRadioButton2.isSelected()) {
                        String myArray = "";
                        for (int i = 0; i < readFilesInPair1.getModel().getSize(); i++) {
                            myArray += (readFilesInPair1.getModel().getElementAt(i) + ",").trim();
                        }
                        
                        myArray = StringUtils.chop(myArray).replaceAll("\"", "");
                        myArray = "\"" + myArray + "\" ";
                        //System.out.println("Read 1: " + myArray);
                        String myArray2 = "";
                        for (int i = 0; i < readFilesInPair2.getModel().getSize(); i++) {
                            myArray2 += (readFilesInPair2.getModel().getElementAt(i) + ",").trim();
                        }
                        myArray2 = StringUtils.chop(myArray2).replaceAll("\"", "");
                        myArray2 = "\"" + myArray2 + "\"";
                        //System.out.println("Read 2: " + myArray);
                        myArray = myArray + myArray2;
                        //System.out.println("Final: " + myArray);
                        
                        cmdList.add(myArray); //--readFilesIn 6
                    }
                    
                    //cmdList.add(txtReadFiles1.getText());//--readFilesIn
                    cmdList.add(jComboBox2.getSelectedItem().toString());//--readFilesCommand 7
                    cmdList.add(jComboBox3.getSelectedItem().toString());//--outSAMunmapped 8
                    cmdList.add(txtOutputDir.getText() +  jTextField1.getText() + ".star.");//--outFileNamePrefix
                    cmdList.add(outSAMtype2.getSelectedItem().toString());//10
                    cmdList.add(twopassMode2.getSelectedItem().toString());//11
                    cmdList.add(jTextField4.getText());//12
                    cmdList.add(jTextField5.getText());//13
                    cmdList.add(fileMode); //14
                    
                    cmdList.add(outBAMsortingBinsN.getText());//15
                    cmdList.add(outSAMmapqUnique.getText());//16
                    publish("\r\nCommand Executed: " + cmdList);
                    
                    if (System.getProperty("os.name").startsWith("Windows")) {

                        //     builder.command("cmd.exe", "/c", "java -Xmx250m -classpath .;./sam-1.103.jar;./jbzip2-0.9.jar uk.ac.babraham.FastQC.FastQCApplication"+fastqPath.getText())
                        //     .directory(new File(STARpath));
                    } else {

                        //
                        //builder.command("sh", "-c", "cd", STARpath);
                        builder.command(cmdList);
                        // SshremoteConnection.executeShell(cmdList);

                        //https://hbctraining.github.io/Intro-to-rnaseq-hpc-O2/lessons/03_alignment.html
                    }
                    builder.redirectErrorStream(true);
                    
                    Process process = builder.start();
                    
                    InputStream is = process.getInputStream();
                    BufferedReader br = new BufferedReader(new InputStreamReader(is));
                    String line = null;
                    while ((line = br.readLine()) != null) {
                        App.LOGGER.info(line + "\r\n");
                        publish("\r\n" + line);
                        
                         if ((line.endsWith("...... FATAL ERROR, exiting")) || (line.endsWith("Killed"))) {
                                break;
                            }
//                            if (line.startsWith("A USER ERROR has occurred:")) {
//                                break;
//                            }
                          if(line.contains("Killed") || line.contains("Aborted") || line.contains("ERROR")){
                                  break;}

                        
                        
                        
                    }
                    
                    if (!isCancelled()) {
                        status = process.waitFor();
                    }
                    
                    process.destroy();
                    
                } catch (IOException | InterruptedException ex) {
                    ex.printStackTrace(new PrintWriter(App.stack));
                    App.LOGGER.error("\r\n ERROR in STAR analysis: " + App.stack);
                    App.textArea.append("\r\n ERROR in STAR analysis: " + App.stack);
                    
                }
                return status;
            }
            
            @Override
            protected void process(java.util.List<String> messages) {
                
                for (String message : messages) {
                    App.textArea.append(message + "\n");
                }
            }
            
            @Override
            protected void done() {
                App.sP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 15), new java.awt.Color(255, 255, 255)));
                
                App.bar.setIndeterminate(false);
            }
            
        };
        
        worker.execute();
        

    }//GEN-LAST:event_buttonSTARAnalysis1ActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        if (clickedFlag == 0) {
            additionalPanel.setVisible(true);
            clickedFlag = 1;
            jLabel19.setIcon(App.icons[2]);
            
        } else if (clickedFlag == 1) {
            additionalPanel.setVisible(false);
            clickedFlag = 0;
            jLabel19.setIcon(App.icons[3]);
            
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Text Files (*.txt)", "txt"));
//        javax.swing.filechooser.FileFilter filter = new javax.swing.filechooser.FileFilter() {
//            public boolean accept(File f) {
//                return f.isDirectory() || f.getName().toLowerCase().endsWith(".txt");
//            }
//
//            public String getDescription() {
//                return "Text Files(*.txt)";
//            }
//        };
        fileChooser.setMultiSelectionEnabled(true);
//        fileChooser.addChoosableFileFilter(filter);

        fileChooser.setAcceptAllFileFilterUsed(false);
        
        int option = fileChooser.showOpenDialog(this);
        
        if (option == JFileChooser.APPROVE_OPTION) {
            
            if (fileChooser.getSelectedFiles() != null) {
                allFiles = fileChooser.getSelectedFiles();
                
                String path = "";
                for (int i = 0; i < allFiles.length; i++) {
                    path += " \"" + allFiles[i].getAbsolutePath() + "\"";
                    //fileNameWithExtension.add(i, allFiles[i].getName());

                }
                
                txtFileChrStartEnd.setText(path);
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        jLabel14.setIcon(App.icons[1]);
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        jLabel14.setIcon(App.icons[0]);
    }//GEN-LAST:event_jLabel14MouseExited

    private void genomeFastaListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genomeFastaListKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_DELETE) {
            int x = genomeFastaList.getSelectedIndex();
            listModelfasta.remove(x);
            
        }
    }//GEN-LAST:event_genomeFastaListKeyPressed

    private void browseOutputDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseOutputDirActionPerformed
              JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setCurrentDirectory(new java.io.File("."));
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            
            String path = fileChooser.getSelectedFile().toString();
            
            txtOutputDir.setText(path + "/");
            
        }
    }//GEN-LAST:event_browseOutputDirActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        //Single read ON
        jButton6.setEnabled(true);

        //Pair read OFF
        listModelreadPair1.clear();
        listModelreadPair2.clear();
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        //Single read OFF
        jButton6.setEnabled(false);
        listModelreadSingle.clear();
        //Pair read ON
        //listModelreadPair1.clear();listModelreadPair2.clear();
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void readFilesInSingleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readFilesInSingleKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_DELETE) {
            listModelreadSingle.remove(readFilesInSingle.getSelectedIndex());

        }
    }//GEN-LAST:event_readFilesInSingleKeyPressed

    private void readFilesInPair1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readFilesInPair1KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_DELETE) {
            listModelreadPair1.remove(readFilesInPair1.getSelectedIndex());

        }
    }//GEN-LAST:event_readFilesInPair1KeyPressed

    private void readFilesInPair2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readFilesInPair2KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_DELETE) {
            listModelreadPair2.remove(readFilesInPair2.getSelectedIndex());

        }
    }//GEN-LAST:event_readFilesInPair2KeyPressed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if(fileSystemCombo.getSelectedIndex()==0){
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fastq Files (*.fq.gz)", "gz"));
        }
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fastq Files (*.fq)", "fq"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fasta Files (*.fa)", "fa"));
        fileChooser.setMultiSelectionEnabled(true);
        fileChooser.setAcceptAllFileFilterUsed(true);

        int option = fileChooser.showOpenDialog(this);

        if (option == JFileChooser.APPROVE_OPTION) {

            if (fileChooser.getSelectedFiles() != null) {
                allFiles = fileChooser.getSelectedFiles();//File[] allfiles

                for (int i = 0; i < allFiles.length; i++) {
                    listModelreadPair2.addElement(" \"" + allFiles[i].getAbsolutePath() + "\"");

                }

            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
         if(fileSystemCombo.getSelectedIndex()==0){
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fastq Files (*.fq.gz)", "gz"));
         }
         fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fastq Files (*.fq)", "fq"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fasta Files (*.fa)", "fa"));
        fileChooser.setMultiSelectionEnabled(true);
        fileChooser.setAcceptAllFileFilterUsed(true);

        int option = fileChooser.showOpenDialog(this);

        if (option == JFileChooser.APPROVE_OPTION) {

            if (fileChooser.getSelectedFiles() != null) {
                allFiles = fileChooser.getSelectedFiles();//File[] allfiles

                for (int i = 0; i < allFiles.length; i++) {
                    listModelreadPair1.addElement(" \"" + allFiles[i].getAbsolutePath() + "\"");

                }

            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
       if(fileSystemCombo.getSelectedIndex()==0){
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fastq Files (*.fq.gz)", "gz"));
       }
       fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fastq Files (*.fq)", "fq"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fasta Files (*.fa)", "fa"));
        
        fileChooser.setMultiSelectionEnabled(true);
        fileChooser.setAcceptAllFileFilterUsed(true);

        int option = fileChooser.showOpenDialog(this);

        if (option == JFileChooser.APPROVE_OPTION) {

            if (fileChooser.getSelectedFiles() != null) {
                allFiles = fileChooser.getSelectedFiles();//File[] allfiles

                for (int i = 0; i < allFiles.length; i++) {
                    listModelreadSingle.addElement(" \"" + allFiles[i].getAbsolutePath() + "\"");

                }

            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void fileSystemComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSystemComboActionPerformed
        if(fileSystemCombo.getSelectedIndex()==0)
        {
            jLabel90.setText("NOTE: User can upload input files in *.fq , *.fa ,or *.gz zipped format.");
            fileMode="exFAT";
        }
        else{
            jLabel90.setText("NOTE: User can upload only unzipped input files in *.fq or *.fa format.");
            fileMode="NTFS";
        }
    }//GEN-LAST:event_fileSystemComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel STARPanel;
    private javax.swing.JPanel additionalPanel;
    private javax.swing.JButton browseGenomeDir;
    private javax.swing.JButton browseGenomeDir1;
    private javax.swing.JButton browseGenomeFastaFiles;
    private javax.swing.JButton browseGtfFile;
    private javax.swing.JButton browseOutputDir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonSTARAnalysis;
    private javax.swing.JButton buttonSTARAnalysis1;
    private javax.swing.JTextField exonParentTranscript;
    private javax.swing.JTextField featureExon;
    private javax.swing.JComboBox<String> fileSystemCombo;
    private javax.swing.JTextField genomeChrBin;
    private javax.swing.JList<String> genomeFastaList;
    private javax.swing.JTextField genomeSAindex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField outBAMsortingBinsN;
    private javax.swing.JTextField outSAMmapqUnique;
    private javax.swing.JComboBox<String> outSAMtype2;
    private javax.swing.JTextField overhangTxt;
    private javax.swing.JList<String> readFilesInPair1;
    private javax.swing.JList<String> readFilesInPair2;
    private javax.swing.JList<String> readFilesInSingle;
    private javax.swing.JTextField runModeTxt;
    private javax.swing.JPanel starStep1Panel;
    private javax.swing.JPanel starStep2Panel;
    private javax.swing.JTextField threadsTxt;
    private javax.swing.JComboBox<String> twopassMode2;
    private javax.swing.JTextField txtFileChrStartEnd;
    private javax.swing.JTextField txtGenomeDir;
    private javax.swing.JTextField txtGenomeDir1;
    private javax.swing.JTextField txtGtfFiles;
    private javax.swing.JTextField txtOutputDir;
    // End of variables declaration//GEN-END:variables
}
