/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package NGSGradle;

import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.io.PrintWriter;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import org.apache.commons.io.FilenameUtils;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author iffy
 */
public class TrimmomaticInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form FastQCInternalFrame
     */
   
    private DefaultListModel listSingleFasta,listPairFasta1,listPairFasta2;
    private File[] allFiles;
    
    public TrimmomaticInternalFrame() {


        listSingleFasta = new DefaultListModel();
        listPairFasta1 = new DefaultListModel();
        listPairFasta2 = new DefaultListModel();
        initComponents();
        
        
        jLabel14.setIcon(App.icons[0]);
        
        buttonGroup1.add(singleRadio);
        buttonGroup1.add(pairRadio);
   

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        trimmomaticScrollPane = new javax.swing.JScrollPane();
        TrimPanel = new javax.swing.JPanel(){

            public void paintComponent(Graphics g){
                super.paintComponent(g);
                g.drawImage(NGSGradle.App.bgLoginMain, 0, 0, null);
            }
        }

        ;
        analyseBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        outputTxt = new javax.swing.JTextField();
        browseOBtn = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        singleRadio = new javax.swing.JRadioButton();
        pairRadio = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        readFilesInSingle = new javax.swing.JList<>(listSingleFasta);
        jScrollPane5 = new javax.swing.JScrollPane();
        readFilesInPair1 = new javax.swing.JList<>(listPairFasta1);
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        readFilesInPair2 = new javax.swing.JList<>(listPairFasta2);
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        adapterfile = new javax.swing.JTextField();
        sliding = new javax.swing.JTextField();
        leading = new javax.swing.JTextField();
        trailing = new javax.swing.JTextField();
        minlen = new javax.swing.JTextField();
        illumniaclip = new javax.swing.JTextField();
        maxinfo = new javax.swing.JTextField();
        crop = new javax.swing.JTextField();
        headcrop = new javax.swing.JTextField();
        thread = new javax.swing.JTextField();
        slidingC = new javax.swing.JCheckBox();
        jLabel38 = new javax.swing.JLabel();
        browseGTFBtn = new javax.swing.JButton();
        headcropC = new javax.swing.JCheckBox();
        threadC = new javax.swing.JCheckBox();
        maxinfoC = new javax.swing.JCheckBox();
        trailingC = new javax.swing.JCheckBox();
        leadingC = new javax.swing.JCheckBox();
        minlenC = new javax.swing.JCheckBox();
        logC = new javax.swing.JCheckBox();
        cropC = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Trimmomatic"));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("TRIMMOMATIC");

        TrimPanel.setBackground(new java.awt.Color(0, 0, 0));
        TrimPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trimmomatic: To trim and crop Illumina (FASTQ) data as well as to remove adapters. ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        analyseBtn.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        analyseBtn.setText("Perform Analysis");
        analyseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyseBtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("HELP?");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Set Output Directory:");

        outputTxt.setEditable(false);

        browseOBtn.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        browseOBtn.setText("...");
        browseOBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseOBtnActionPerformed(evt);
            }
        });

        warningLabel.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 0, 0));

        singleRadio.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        singleRadio.setForeground(new java.awt.Color(255, 255, 255));
        singleRadio.setSelected(true);
        singleRadio.setText("readFilesIn (Single end reads)");
        singleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleRadioActionPerformed(evt);
            }
        });

        pairRadio.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        pairRadio.setForeground(new java.awt.Color(255, 255, 255));
        pairRadio.setText("readFilesIn (Paired end reads)");
        pairRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pairRadioActionPerformed(evt);
            }
        });

        readFilesInSingle.setBorder(javax.swing.BorderFactory.createTitledBorder("All sample(s) single end reads"));
        readFilesInSingle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        readFilesInSingle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                readFilesInSingleKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(readFilesInSingle);

        readFilesInPair1.setBorder(javax.swing.BorderFactory.createTitledBorder("All sample(s) read 1 only"));
        readFilesInPair1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        readFilesInPair1.setEnabled(false);
        readFilesInPair1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                readFilesInPair1KeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(readFilesInPair1);

        jButton6.setText("...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("...");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        readFilesInPair2.setBorder(javax.swing.BorderFactory.createTitledBorder("All sample(s) read 2 only"));
        readFilesInPair2.setEnabled(false);
        readFilesInPair2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                readFilesInPair2KeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(readFilesInPair2);

        jButton8.setText("...");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Trimmomatic Parameters:");

        jLabel32.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("phred Encoding:");

        jLabel33.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Adapter Fasta File:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-phred33", "-phred64" }));

        adapterfile.setEditable(false);

        sliding.setText("4:15");

        leading.setText("3");

        trailing.setText("3");

        minlen.setText("36");

        illumniaclip.setText("2:30:10");

        maxinfo.setEnabled(false);

        crop.setEnabled(false);

        headcrop.setEnabled(false);

        thread.setEnabled(false);

        slidingC.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        slidingC.setForeground(new java.awt.Color(255, 255, 255));
        slidingC.setSelected(true);
        slidingC.setText("SLIDINGWINDOW:");
        slidingC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                slidingCItemStateChanged(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("ILLUMNIACLIP:");

        browseGTFBtn.setText("...");
        browseGTFBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseGTFBtnActionPerformed(evt);
            }
        });

        headcropC.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        headcropC.setForeground(new java.awt.Color(255, 255, 255));
        headcropC.setText("HEADCROP:");
        headcropC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                headcropCItemStateChanged(evt);
            }
        });

        threadC.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        threadC.setForeground(new java.awt.Color(255, 255, 255));
        threadC.setText("THREAD(S):");

        maxinfoC.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        maxinfoC.setForeground(new java.awt.Color(255, 255, 255));
        maxinfoC.setText("MAXINFO:");
        maxinfoC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                maxinfoCItemStateChanged(evt);
            }
        });

        trailingC.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        trailingC.setForeground(new java.awt.Color(255, 255, 255));
        trailingC.setSelected(true);
        trailingC.setText("TRAILING:");
        trailingC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                trailingCItemStateChanged(evt);
            }
        });

        leadingC.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        leadingC.setForeground(new java.awt.Color(255, 255, 255));
        leadingC.setSelected(true);
        leadingC.setText("LEADING:");
        leadingC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                leadingCItemStateChanged(evt);
            }
        });

        minlenC.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        minlenC.setForeground(new java.awt.Color(255, 255, 255));
        minlenC.setSelected(true);
        minlenC.setText("MINLEN:");
        minlenC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                minlenCItemStateChanged(evt);
            }
        });

        logC.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        logC.setForeground(new java.awt.Color(255, 255, 255));
        logC.setText("Generate Log File?");

        cropC.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        cropC.setForeground(new java.awt.Color(255, 255, 255));
        cropC.setText("CROP:");
        cropC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cropCItemStateChanged(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TrimPanelLayout = new javax.swing.GroupLayout(TrimPanel);
        TrimPanel.setLayout(TrimPanelLayout);
        TrimPanelLayout.setHorizontalGroup(
            TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(TrimPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(TrimPanelLayout.createSequentialGroup()
                        .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel38)
                            .addComponent(maxinfoC)
                            .addComponent(headcropC)
                            .addGroup(TrimPanelLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(88, 88, 88))
                            .addComponent(leadingC)
                            .addComponent(logC)
                            .addComponent(slidingC))
                        .addGap(30, 30, 30)
                        .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TrimPanelLayout.createSequentialGroup()
                                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(sliding)
                                    .addComponent(headcrop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(maxinfo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(illumniaclip, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leading, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(trailingC)
                                    .addComponent(cropC)
                                    .addComponent(minlenC))
                                .addGap(18, 18, 18)
                                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(trailing, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(minlen)
                                    .addComponent(crop))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(TrimPanelLayout.createSequentialGroup()
                                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(TrimPanelLayout.createSequentialGroup()
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(70, 70, 70)
                                            .addComponent(threadC)
                                            .addGap(18, 18, 18)
                                            .addComponent(thread))
                                        .addGroup(TrimPanelLayout.createSequentialGroup()
                                            .addComponent(adapterfile, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(browseGTFBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(TrimPanelLayout.createSequentialGroup()
                                        .addGap(401, 401, 401)
                                        .addComponent(analyseBtn)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(TrimPanelLayout.createSequentialGroup()
                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TrimPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TrimPanelLayout.createSequentialGroup()
                                .addComponent(singleRadio)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6))
                            .addGroup(TrimPanelLayout.createSequentialGroup()
                                .addComponent(pairRadio)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8))
                            .addGroup(TrimPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outputTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(browseOBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(TrimPanelLayout.createSequentialGroup()
                        .addGap(1183, 1183, 1183)
                        .addComponent(jLabel14)))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TrimPanelLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(452, Short.MAX_VALUE)))
        );
        TrimPanelLayout.setVerticalGroup(
            TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrimPanelLayout.createSequentialGroup()
                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TrimPanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outputTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(browseOBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TrimPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addGap(81, 81, 81)))
                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(singleRadio)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pairRadio)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threadC)
                    .addComponent(thread, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(adapterfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseGTFBtn))
                .addGap(18, 18, 18)
                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(illumniaclip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trailingC)
                    .addComponent(trailing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leadingC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slidingC)
                    .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sliding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(minlenC)
                        .addComponent(minlen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxinfoC)
                    .addComponent(maxinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cropC)
                    .addComponent(crop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headcropC)
                    .addComponent(headcrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TrimPanelLayout.createSequentialGroup()
                        .addComponent(logC)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TrimPanelLayout.createSequentialGroup()
                        .addComponent(analyseBtn)
                        .addGap(49, 49, 49)))
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(TrimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TrimPanelLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(906, Short.MAX_VALUE)))
        );

        trimmomaticScrollPane.setViewportView(TrimPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trimmomaticScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1319, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trimmomaticScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analyseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyseBtnActionPerformed

        boolean check=true;
        if (outputTxt.getText().isBlank()) {
            warningLabel.setText("**ERROR: Select Output Directory");
            check = false;
        }
        if (singleRadio.isSelected()) {

            if (listSingleFasta.isEmpty()) {
                warningLabel.setText("**ERROR: Input read(s)/Sample(s)");
                check = false;
            }
        } else if (pairRadio.isSelected()) {

            if ((listPairFasta1.isEmpty()) || (listPairFasta2.isEmpty())) {
                warningLabel.setText("**ERROR: Input read(s)/Sample(s)");
                check = false;
            } else {

                if (listPairFasta1.size() != listPairFasta2.size()) {
                    warningLabel.setText("**ERROR: Samples for Read 1 and Read 2 pairs must be equal in number");

                    check = false;
                }

            }
        }//pair

if (adapterfile.getText().isBlank()){
warningLabel.setText("**ERROR: Input Adapter File");
                check = false;
}        
        ////
        if(check==true)
        {   

            warningLabel.setText("");
        App.bar.setIndeterminate(true);

        App.sP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "In Progress:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 15), new java.awt.Color(255, 255, 255)));

        SwingWorker<?, ?> worker = new SwingWorker<Integer, String>() {

            private int status;

            @Override
            protected Integer doInBackground() {
                try {
                    //FASTQC Windows :Dir_with_FastQC>java -Xmx250m -classpath .;./sam-1.103.jar;./jbzip2-0.9.jar uk.ac.babraham.FastQC.FastQCApplication ju.fq
                    ProcessBuilder builder = new ProcessBuilder();

                    List<String> cmdList = new ArrayList<String>();
                    // adding command and args to the list
                    cmdList.add("sh");
                    cmdList.add(System.getProperty("user.dir").concat("/bin/trimmomatic.sh"));
                    cmdList.add(App.Trimmomatic_PATH); //$1
                    
                    
                    String myArray = "";
                    
                    if (singleRadio.isSelected()) {
                        cmdList.add("SINGLE"); //2
                        for (int i = 0; i < readFilesInSingle.getModel().getSize(); i++) {

                            myArray += (readFilesInSingle.getModel().getElementAt(i) + ",");
                           
                        }//endFor

                        myArray = StringUtils.chop(myArray).replaceAll("\"", "");
                        myArray = myArray.trim();
                        cmdList.add(myArray); //3
                    } else if (pairRadio.isSelected()) {
                        cmdList.add("PAIR");//2
                        if (readFilesInPair1.getModel().getSize() == readFilesInPair2.getModel().getSize()) {
                            for (int i = 0; i < readFilesInPair1.getModel().getSize(); i++) {

                                myArray += (readFilesInPair1.getModel().getElementAt(i).trim() + "#" + readFilesInPair2.getModel().getElementAt(i).trim() + ",");

                            }//for

                            myArray = StringUtils.chop(myArray).replaceAll("\"", "");
                            myArray = myArray.trim();

                            cmdList.add(myArray); //3
                        }
                    }//endif

                    cmdList.add(outputTxt.getText());//4

                    cmdList.add(jComboBox1.getSelectedItem().toString());//5
                    cmdList.add((logC.isSelected()?"YES":"NO"));
cmdList.add(adapterfile.getText());//6
cmdList.add(illumniaclip.getText());//7
cmdList.add(sliding.getText());//8
cmdList.add(leading.getText());//9
cmdList.add(trailing.getText());//10
cmdList.add(minlen.getText());//11
cmdList.add(thread.getText());//12
cmdList.add(maxinfo.getText());//13
cmdList.add(crop.getText());//14
cmdList.add(headcrop.getText());//15




                   

                    builder.command(cmdList);

                    builder.redirectErrorStream(true);

                    Process process = builder.start();

                    InputStream is = process.getInputStream();
                    BufferedReader br = new BufferedReader(new InputStreamReader(is));
                    String line = null;
                    while ((line = br.readLine()) != null && !isCancelled()) {
                        App.LOGGER.info(line + "\r\n");
                        publish(line);

                    }

                    if (!isCancelled()) {
                        status = process.waitFor();
                    }

                    process.destroy();
                } catch (IOException | InterruptedException ex) {
                    ex.printStackTrace(new PrintWriter(App.stack));
                    App.LOGGER.error("\r\n ERROR in FastQC analysis: " + App.stack);
                    App.textArea.append("\r\n ERROR in FastQC analysis: " + App.stack);

                }
                return status;
            }

            @Override
            protected void process(java.util.List<String> messages) {

                for (String message : messages) {
                    App.textArea.append(message + "\n");
                }

            }

            @Override
            protected void done() {
                App.sP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 15), new java.awt.Color(255, 255, 255)));

                App.bar.setIndeterminate(false);

            }

        };

        worker.execute();
    }
        //   fastqcTable.
        /*
        try {
            //FASTQC Windows :Dir_with_FastQC>java -Xmx250m -classpath .;./sam-1.103.jar;./jbzip2-0.9.jar uk.ac.babraham.FastQC.FastQCApplication ju.fq
            ProcessBuilder builder = new ProcessBuilder();

            List<String> cmdList = new ArrayList<String>();
            // adding command and args to the list
            cmdList.add("sh");
            cmdList.add(System.getProperty("user.dir").concat("/bin/fastqc.sh"));
            cmdList.add(App.FastQC_PATH); //$1

            cmdList.add(fastqTxt.getText());
            cmdList.add(outputTxt.getText());

            App.textArea.append("\r\n" + cmdList);

            if (System.getProperty("os.name").startsWith("Windows")) {

                //  builder2.command("cmd.exe", "/c", "java -Xmx250m -classpath .;./sam-1.103.jar;./jbzip2-0.9.jar uk.ac.babraham.FastQC.FastQCApplication" + fastqTxt.getText())
                //        .directory(new File(path));
            } else {
                //

                // builder2.command("sh", "-c", "fastqc", fastqTxt.getText()).directory(new File(path));
                builder.command(cmdList);
            }
            builder.redirectErrorStream(true);

            Process process = builder.start();

            InputStream is = process.getInputStream();
            BufferedReader br = new BufferedReader(new InputStreamReader(is));
            String line = null;
            while ((line = br.readLine()) != null) {
                App.LOGGER.info(line + "\r\n");
                App.textArea.append(line + "\r\n");

            }

            //RESULTS
            // fileNameWithoutExtension.forEach(x -> x.concat("_fastqc.html"));
            // System.out.println("IN ANALYSIS: "+fileNameWithoutExtension);
            resultsCombo.setModel(new DefaultComboBoxModel<String>(fileNameWithoutExtension.toArray(new String[0])));
            resultsCombo.setEnabled(true);
            flag = true;
            int r = process.waitFor(); // Let the process finish.
            if (r == 0) { // No error
                // run cmd2.
            }
            process.destroy();
        } catch (IOException | InterruptedException ex) {
            App.LOGGER.error("ERROR in FastQC Analysis: " + ex);
            ex.printStackTrace();
            App.textArea.append("ERROR in FastQC Analysis: " + ex);
        }
         */
    }//GEN-LAST:event_analyseBtnActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked

        try {
            Desktop.getDesktop().open(new File(System.getProperty("user.dir").concat("/bin/FastQC_Manual.pdf")));
        } catch (IOException ex) {
            App.LOGGER.error("\r\nERROR loading FASTQC mannual file: " + ex);
            App.textArea.append("\r\nERROR loading FASTQC mannual file: " + ex);
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void browseOBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseOBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setCurrentDirectory(new java.io.File("."));
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {

            String path = fileChooser.getSelectedFile().toString();

            outputTxt.setText(path + "/");

        }
    }//GEN-LAST:event_browseOBtnActionPerformed

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        jLabel14.setIcon(App.icons[1]);
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        jLabel14.setIcon(App.icons[0]);
    }//GEN-LAST:event_jLabel14MouseExited

    private void singleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleRadioActionPerformed
        //Pair read OFF
        listPairFasta1.clear();
        listPairFasta2.clear();
        readFilesInPair1.setEnabled(false);
        readFilesInPair2.setEnabled(false);
        jButton7.setEnabled(false); 
        jButton8.setEnabled(false);
                
        readFilesInSingle.setEnabled(true);jButton6.setEnabled(true);
        
        
    }//GEN-LAST:event_singleRadioActionPerformed

    private void pairRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pairRadioActionPerformed
        //Single read OFF
        listSingleFasta.clear();
        readFilesInSingle.setEnabled(false);jButton6.setEnabled(false);
         readFilesInPair1.setEnabled(true);
        readFilesInPair2.setEnabled(true);
        jButton7.setEnabled(true); 
        jButton8.setEnabled(true);
        
    }//GEN-LAST:event_pairRadioActionPerformed

    private void readFilesInSingleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readFilesInSingleKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_DELETE) {
            listSingleFasta.remove(readFilesInSingle.getSelectedIndex());

        }
    }//GEN-LAST:event_readFilesInSingleKeyPressed

    private void readFilesInPair1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readFilesInPair1KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_DELETE) {
            listPairFasta1.remove(readFilesInPair1.getSelectedIndex());

        }
    }//GEN-LAST:event_readFilesInPair1KeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fastq Files (*.fq)", "fq"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fasta Files (*.gz)", "gz"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fasta Files (*.bz2)", "bz2"));

        fileChooser.setMultiSelectionEnabled(true);
        fileChooser.setAcceptAllFileFilterUsed(true);

        int option = fileChooser.showOpenDialog(this);

        if (option == JFileChooser.APPROVE_OPTION) {

            if (fileChooser.getSelectedFiles() != null) {
                allFiles = fileChooser.getSelectedFiles();//File[] allfiles

                for (int i = 0; i < allFiles.length; i++) {
                    listSingleFasta.addElement(" \"" + allFiles[i].getAbsolutePath() + "\"");
                }

            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fastq Files (*.fq)", "fq"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fasta Files (*.gz)", "gz"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fasta Files (*.bz2)", "bz2"));

        fileChooser.setMultiSelectionEnabled(true);
        fileChooser.setAcceptAllFileFilterUsed(true);

        int option = fileChooser.showOpenDialog(this);

        if (option == JFileChooser.APPROVE_OPTION) {

            if (fileChooser.getSelectedFiles() != null) {
                allFiles = fileChooser.getSelectedFiles();//File[] allfiles

                for (int i = 0; i < allFiles.length; i++) {
                    listPairFasta1.addElement(" \"" + allFiles[i].getAbsolutePath() + "\"");
                }

            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void readFilesInPair2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readFilesInPair2KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_DELETE) {
            listPairFasta2.remove(readFilesInPair2.getSelectedIndex());

        }
    }//GEN-LAST:event_readFilesInPair2KeyPressed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
     fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fastq Files (*.fq)", "fq"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fasta Files (*.gz)", "gz"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fasta Files (*.bz2)", "bz2"));
    fileChooser.setMultiSelectionEnabled(true);
        fileChooser.setAcceptAllFileFilterUsed(true);

        int option = fileChooser.showOpenDialog(this);

        if (option == JFileChooser.APPROVE_OPTION) {

            if (fileChooser.getSelectedFiles() != null) {
                allFiles = fileChooser.getSelectedFiles();//File[] allfiles

                for (int i = 0; i < allFiles.length; i++) {
                    listPairFasta2.addElement(" \"" + allFiles[i].getAbsolutePath() + "\"");
                }

            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void browseGTFBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseGTFBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
fileChooser.setCurrentDirectory(new File(App.Trimmomatic_PATH));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Fasta Files (*.fa)", "fa"));
        fileChooser.setAcceptAllFileFilterUsed(false);
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            if (fileChooser.getSelectedFile() != null) {

                adapterfile.setText(fileChooser.getSelectedFile().toString());

            }
        }
    }//GEN-LAST:event_browseGTFBtnActionPerformed

    private void slidingCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_slidingCItemStateChanged
       if(slidingC.isSelected())
           sliding.setEnabled(true);
       else
           sliding.setEnabled(false);
    }//GEN-LAST:event_slidingCItemStateChanged

    private void leadingCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_leadingCItemStateChanged
       if(leadingC.isSelected())
           leading.setEnabled(true);
       else
           leading.setEnabled(false);
    }//GEN-LAST:event_leadingCItemStateChanged

    private void trailingCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_trailingCItemStateChanged
       if(trailingC.isSelected())
           trailing.setEnabled(true);
       else
           trailing.setEnabled(false);
    }//GEN-LAST:event_trailingCItemStateChanged

    private void minlenCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_minlenCItemStateChanged
if(minlenC.isSelected())
           minlen.setEnabled(true);
       else
           minlen.setEnabled(false);
    }//GEN-LAST:event_minlenCItemStateChanged

    private void maxinfoCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_maxinfoCItemStateChanged
if(maxinfoC.isSelected())
           maxinfo.setEnabled(true);
       else
           maxinfo.setEnabled(false);
    }//GEN-LAST:event_maxinfoCItemStateChanged

    private void cropCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cropCItemStateChanged
if(cropC.isSelected())
           crop.setEnabled(true);
       else
           crop.setEnabled(false);
    }//GEN-LAST:event_cropCItemStateChanged

    private void headcropCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_headcropCItemStateChanged
if(headcropC.isSelected())
           headcrop.setEnabled(true);
       else
           headcrop.setEnabled(false);
    }//GEN-LAST:event_headcropCItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
singleRadio.setSelected(true); pairRadio.setSelected(false);
listSingleFasta.clear(); listPairFasta1.clear(); listPairFasta2.clear();
jComboBox1.setSelectedIndex(0);

adapterfile.setText(""); illumniaclip.setText("::");
threadC.setSelected(false);thread.setEnabled(false);thread.setText("");
slidingC.setSelected(false);sliding.setEnabled(false);sliding.setText(":");
leadingC.setSelected(false);leading.setEnabled(false);leading.setText("");
trailingC.setSelected(false);trailing.setEnabled(false);trailing.setText("");
minlenC.setSelected(false);minlen.setEnabled(false);minlen.setText("");
maxinfoC.setSelected(false);maxinfo.setEnabled(false);maxinfo.setText("");
cropC.setSelected(false);crop.setEnabled(false);crop.setText("");
headcropC.setSelected(false);headcrop.setEnabled(false);headcrop.setText("");
logC.setSelected(false);







    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TrimPanel;
    private javax.swing.JTextField adapterfile;
    private javax.swing.JButton analyseBtn;
    private javax.swing.JButton browseGTFBtn;
    private javax.swing.JButton browseOBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField crop;
    private javax.swing.JCheckBox cropC;
    private javax.swing.JTextField headcrop;
    private javax.swing.JCheckBox headcropC;
    private javax.swing.JTextField illumniaclip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField leading;
    private javax.swing.JCheckBox leadingC;
    private javax.swing.JCheckBox logC;
    private javax.swing.JTextField maxinfo;
    private javax.swing.JCheckBox maxinfoC;
    private javax.swing.JTextField minlen;
    private javax.swing.JCheckBox minlenC;
    private javax.swing.JTextField outputTxt;
    private javax.swing.JRadioButton pairRadio;
    private javax.swing.JList<String> readFilesInPair1;
    private javax.swing.JList<String> readFilesInPair2;
    private javax.swing.JList<String> readFilesInSingle;
    private javax.swing.JRadioButton singleRadio;
    private javax.swing.JTextField sliding;
    private javax.swing.JCheckBox slidingC;
    private javax.swing.JTextField thread;
    private javax.swing.JCheckBox threadC;
    private javax.swing.JTextField trailing;
    private javax.swing.JCheckBox trailingC;
    private javax.swing.JScrollPane trimmomaticScrollPane;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
